"""Embedded LAN-only PulseDeck Admin interface."""

ADMIN_HTML = r'''<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PulseDeck Admin</title>
<style>
:root{color-scheme:dark;--bg:#0b0e13;--panel:#141922;--panel2:#1b2230;--text:#e9edf4;--muted:#8e99a9;--line:#2a3444;--good:#62d38b;--bad:#ff7474;--accent:#7aa2ff}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 system-ui,-apple-system,sans-serif}main{max-width:1100px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}h1{font-size:24px;margin:0}h2{font-size:16px;margin:0 0 14px}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.card{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:16px;margin-bottom:12px}.metric{font-size:22px;font-weight:650;margin-top:6px}.ok{color:var(--good)}.bad{color:var(--bad)}label{display:block;color:var(--muted);margin:10px 0 5px}input,select,button{font:inherit}input,select{width:100%;background:#0e131b;border:1px solid var(--line);color:var(--text);padding:10px;border-radius:8px}input[type=checkbox]{width:auto;margin-right:8px}button{border:0;border-radius:8px;padding:10px 14px;background:var(--accent);color:#07101f;font-weight:700;cursor:pointer}button.secondary{background:var(--panel2);color:var(--text);border:1px solid var(--line)}button.danger{background:#5b2528;color:#ffd9da}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.actions{display:flex;gap:8px;align-items:center;margin-top:14px;flex-wrap:wrap}.status{min-height:20px;color:var(--muted)}#app,#login{display:none}.pill{display:inline-block;padding:3px 8px;border-radius:999px;background:var(--panel2);font-size:12px}.key-state{padding:8px 10px;background:#0e131b;border-radius:8px;color:var(--muted)}@media(max-width:680px){main{padding:14px}.row{grid-template-columns:1fr}}
</style></head><body><main>
<div class="top"><div><h1>PulseDeck Admin</h1><div class="muted">Administration locale du hub</div></div><button id="logout" class="secondary" style="display:none">Déconnexion</button></div>
<section id="login" class="card"><h2>Connexion</h2><label>Mot de passe administrateur</label><input id="loginPassword" type="password" autocomplete="current-password"><div class="actions"><button onclick="login()">Connexion</button><span id="loginStatus" class="status"></span></div></section>
<section id="app">
<div class="grid">
<div class="card"><div class="muted">Hub</div><div id="hubVersion" class="metric">—</div><div id="hubUptime" class="muted"></div></div>
<div class="card"><div class="muted">MQTT</div><div id="mqttState" class="metric">—</div><div id="mqttTarget" class="muted"></div></div>
<div class="card"><div class="muted">Weather</div><div id="weatherState" class="metric">—</div><div id="weatherDetail" class="muted"></div></div>
<div class="card"><div class="muted">Système</div><div id="systemMemory" class="metric">—</div><div id="systemDisk" class="muted"></div></div>
</div>
<div class="card"><h2>Weather · OpenWeather One Call 4.0</h2>
<label><input id="weatherEnabled" type="checkbox">Collector activé</label>
<div class="row"><div><label>Lieu à rechercher</label><input id="locationQuery" placeholder="Yutz, France"></div><div><label>Résultat</label><select id="locationResult"><option value="">Coordonnées actuelles</option></select></div></div>
<div class="row"><div><label>Latitude</label><input id="latitude" type="number" step="any"></div><div><label>Longitude</label><input id="longitude" type="number" step="any"></div></div>
<label>Nom affiché</label><input id="locationName">
<label>Clé API OpenWeather</label><input id="apiKey" type="password" autocomplete="new-password" placeholder="Laisser vide pour conserver la clé actuelle"><div id="keyState" class="key-state"></div>
<div class="row"><div><label>Langue</label><input id="lang" value="fr"></div><div><label>Timeout HTTP (s)</label><input id="requestTimeout" type="number" min="1" max="60"></div></div>
<div class="row"><div><label>Current (s)</label><input id="currentInterval" type="number" min="600"></div><div><label>Hourly (s)</label><input id="hourlyInterval" type="number" min="600"></div></div>
<label>Daily (s)</label><input id="dailyInterval" type="number" min="600">
<div class="actions"><button class="secondary" onclick="geocode()">Résoudre le lieu</button><button class="secondary" onclick="testWeather()">Tester</button><button onclick="saveWeather()">Tester + enregistrer</button><span id="weatherFormStatus" class="status"></span></div>
</div>
<div class="card"><h2>Dernière activité Weather</h2><div id="weatherHealth" class="muted">—</div></div>
<div class="card"><h2>Sécurité Admin</h2><div class="row"><div><label>Mot de passe actuel</label><input id="currentPassword" type="password" autocomplete="current-password"></div><div><label>Nouveau mot de passe (12+ caractères)</label><input id="newPassword" type="password" autocomplete="new-password"></div></div><div class="actions"><button class="secondary" onclick="changePassword()">Changer le mot de passe</button><span id="passwordStatus" class="status"></span></div></div>
</section>
<script>
const $=id=>document.getElementById(id);const api=(url,opt={})=>fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json','X-PulseDeck-CSRF':'1',...(opt.headers||{})},...opt});
function fmtAge(ts){if(!ts)return 'jamais';const s=Math.max(0,Math.floor(Date.now()/1000-ts));if(s<60)return s+' s';if(s<3600)return Math.floor(s/60)+' min';return Math.floor(s/3600)+' h'}
async function login(){const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({password:$('loginPassword').value})});if(!r.ok){$('loginStatus').textContent='Échec de connexion';return} $('loginPassword').value='';await boot()}
async function logout(){await api('/api/auth/logout',{method:'POST',body:'{}'});location.reload()}
async function boot(){const r=await api('/api/status');if(r.status===401){$('login').style.display='block';$('app').style.display='none';$('logout').style.display='none';return}if(!r.ok)return; $('login').style.display='none';$('app').style.display='block';$('logout').style.display='inline-block';renderStatus(await r.json());await loadWeather()}
function renderStatus(s){$('hubVersion').textContent='v'+s.version;$('hubUptime').textContent='uptime '+Math.floor(s.uptime_seconds/60)+' min';$('mqttState').textContent=s.mqtt.connected?'online':'offline';$('mqttState').className='metric '+(s.mqtt.connected?'ok':'bad');$('mqttTarget').textContent=s.mqtt.host+':'+s.mqtt.port;const w=s.weather;$('weatherState').textContent=w.state;$('weatherState').className='metric '+(w.state==='online'?'ok':(w.state==='disabled'?'':'bad'));$('weatherDetail').textContent=(w.hourly_records??'—')+' h / '+(w.daily_records??'—')+' j';$('systemMemory').textContent=s.system.memory_available_mb+' MiB libres';$('systemDisk').textContent=s.system.disk_free_gb+' GiB libres';$('weatherHealth').textContent='current '+fmtAge(w.last_current)+' · hourly '+fmtAge(w.last_hourly)+' · daily '+fmtAge(w.last_daily)+(w.last_error?' · erreur '+w.last_error_kind+': '+w.last_error:'')}
async function loadWeather(){const r=await api('/api/weather/config');if(!r.ok)return;const w=await r.json();$('weatherEnabled').checked=w.enabled;$('latitude').value=w.latitude??'';$('longitude').value=w.longitude??'';$('locationName').value=w.location_name||'';$('lang').value=w.lang;$('requestTimeout').value=w.request_timeout;$('currentInterval').value=w.current_interval;$('hourlyInterval').value=w.hourly_interval;$('dailyInterval').value=w.daily_interval;$('keyState').textContent=w.api_key_configured?'Clé configurée (masquée)':'Aucune clé configurée'}
function weatherBody(){return {enabled:$('weatherEnabled').checked,latitude:$('latitude').value===''?null:Number($('latitude').value),longitude:$('longitude').value===''?null:Number($('longitude').value),location_name:$('locationName').value.trim(),api_key:$('apiKey').value.trim()||null,lang:$('lang').value.trim(),current_interval:Number($('currentInterval').value),hourly_interval:Number($('hourlyInterval').value),daily_interval:Number($('dailyInterval').value),hourly_hours:48,daily_days:10,request_timeout:Number($('requestTimeout').value)}}
async function geocode(){const q=$('locationQuery').value.trim();if(!q)return;const r=await api('/api/weather/geocode',{method:'POST',body:JSON.stringify({query:q,api_key:$('apiKey').value.trim()||null})});const out=$('weatherFormStatus');if(!r.ok){out.textContent=(await r.json()).detail||'Échec géocodage';return}const data=await r.json(),sel=$('locationResult');sel.innerHTML='';data.results.forEach((x,i)=>{const o=document.createElement('option');o.value=i;o.textContent=x.label;sel.appendChild(o)});sel.onchange=()=>pickLocation(data.results[Number(sel.value)]);if(data.results.length)pickLocation(data.results[0]);out.textContent=data.results.length+' résultat(s)'}
function pickLocation(x){if(!x)return;$('latitude').value=x.latitude;$('longitude').value=x.longitude;$('locationName').value=x.label}
async function testWeather(){const out=$('weatherFormStatus');out.textContent='Test…';const r=await api('/api/weather/test',{method:'POST',body:JSON.stringify(weatherBody())});const d=await r.json();out.textContent=r.ok?('OK · '+d.temperature_c+' °C · hourly '+d.hourly_records):(d.detail||'Échec')}
async function saveWeather(){const out=$('weatherFormStatus');out.textContent='Validation et sauvegarde…';const r=await api('/api/weather/config',{method:'POST',body:JSON.stringify(weatherBody())});const d=await r.json();if(!r.ok){out.textContent=d.detail||'Échec';return} $('apiKey').value='';out.textContent='Configuration appliquée';await loadWeather();setTimeout(boot,500)}
async function changePassword(){const out=$('passwordStatus');const r=await api('/api/auth/password',{method:'POST',body:JSON.stringify({current_password:$('currentPassword').value,new_password:$('newPassword').value})});const d=await r.json();if(!r.ok){out.textContent=d.detail||'Échec';return}$('currentPassword').value='';$('newPassword').value='';out.textContent='Mot de passe modifié'}
$('logout').onclick=logout;$('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login()});boot();setInterval(()=>{if($('app').style.display!=='none')api('/api/status').then(r=>r.ok?r.json():null).then(s=>s&&renderStatus(s))},10000);
</script></main></body></html>'''
